-- MySQL Script generated by MySQL Workbench
-- Mon Aug 10 09:19:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DiKhSQL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DiKhSQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiKhSQL` DEFAULT CHARACTER SET utf8 ;
USE `DiKhSQL` ;

-- -----------------------------------------------------
-- Table `DiKhSQL`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiKhSQL`.`Events` ;

CREATE TABLE IF NOT EXISTS `exam_db`.`Events` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiKhSQL`.`Appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiKhSQL`.`Appointments` ;

CREATE TABLE IF NOT EXISTS `exam_db`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `Events_id` INT NOT NULL,
  PRIMARY KEY (`idAppointments`, `Events_id`),
  INDEX `fk_Appointments_Events_idx` (`Events_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Events`
    FOREIGN KEY (`Events_id`)
    REFERENCES `exam_db`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
