-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 16:55:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

create database if not exists nzappointments;

USE `nzappointments` ;

-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS`events` (
  `idevents` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`
(
    `idappointments`  INT          NOT NULL,
    `appointmentName` VARCHAR(45)  NOT NULL,
    `date`            DATETIME     NOT NULL,
    `events_idevents` INT          NOT NULL,
    `userName`        VARCHAR(256) NOT NULL,
    PRIMARY KEY (`idappointments`, `events_idevents`)
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
