-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 16:59:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ah` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ah`.`Events` (
  `idevents` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `decription` VARCHAR(2048) NULL,
  `Eventscol` VARCHAR(45) NULL,
  `Eventscol1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appoitments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ah`.`appoitments` (
  `idappoitments` INT NOT NULL,
  `appoitmentName` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `events_idevents` INT NULL,
  `users_idusers` INT NULL,
  `appoitmentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idappoitments`, `Events_idevents`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
