-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 16:59:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `idevents` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `decription` VARCHAR(2048) NULL,
  `Eventscol` VARCHAR(45) NULL,
  `Eventscol1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appoitments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appoitments` (
  `idappoitments` INT NOT NULL,
  `appoitmentName` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `events_idevents` INT NULL,
  `users_idusers` INT NULL,
  `appoitmentscol` VARCHAR(45) NULL,
  `Events_idevents` INT NOT NULL,
  PRIMARY KEY (`idappoitments`, `Events_idevents`),
  INDEX `fk_appoitments_Events_idx` (`Events_idevents` ASC) VISIBLE,
  CONSTRAINT `fk_appoitments_Events`
    FOREIGN KEY (`Events_idevents`)
    REFERENCES `mydb`.`Events` (`idevents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
